"""Add hotel, room type, and rate adjustment models

Revision ID: b9f2db0b0c48
Revises: cc4729088855
Create Date: 2026-02-06 16:07:07.203286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f2db0b0c48'
down_revision: Union[str, None] = 'cc4729088855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
